### ISSUE TITLE
Release tracker: Notion 2.0.15

### ISSUE THREAD

**Issue by vtenfys** [davidbailey00/notion-linux#38]
Issues blocking this release:

- [x] ~~Notion 2.0.13+ depends on a fork of `better-sqlite3` which doesn't seem to build properly for arm64 - instead it produces x86_64 binaries and the app fails to launch on arm64~~ (see below)
- [x] Use my MacBook instead of CI to produce arm64 builds and upload these to Gemfury manually
- [x] Notion Enhancer doesn't work out-of-the-box so the `notion-enhanced` package is broken - see [hack notion-enhancer v0.10.2 to work with notion's v2.0.13 app](https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041) for how to work around this
- [ ] Notion Enhancer needs to be updated to support 2.0.13+

Non-blockers, but nice to have:

- [ ] `better-sqlite3` takes a very long time to build - possible to use prebuilt binaries?

Notes:

- Notion 2.0.14 appears to be incompatible with Electron 12 - same with 2.0.15?

**Comment by vtenfys** [comment]
Help would be appreciated if anyone has more knowledge in cross compililation using `node-gyp`
